// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Accueil → Carousel*
 */
export interface AccueilDocumentDataCarouselItem {
  /**
   * Image field in *Accueil → Carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type AccueilDocumentDataSlicesSlice =
  | TexteImageLargeSlice
  | TexteCartesVerticalesSlice
  | TexteCartesGrilleSlice;

/**
 * Content for Accueil documents
 */
interface AccueilDocumentData {
  /**
   * Titre première ligne field in *Accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.titre_premiere_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *Accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.titre_deuxieme_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Carousel field in *Accueil*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.carousel[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<Simplify<AccueilDocumentDataCarouselItem>>;

  /**
   * Formulaire de contact field in *Accueil*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.formulaire_de_contact
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  formulaire_de_contact: prismic.ContentRelationshipField<"formulaire_de_contact">;

  /**
   * Slice Zone field in *Accueil*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AccueilDocumentDataSlicesSlice> /**
   * Meta Description field in *Accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: accueil.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Accueil*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: accueil.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Accueil document from Prismic
 *
 * - **API ID**: `accueil`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AccueilDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AccueilDocumentData>,
    "accueil",
    Lang
  >;

/**
 * Item in *Coup de coeur → Carousel*
 */
export interface CoupDeCoeurDocumentDataCarouselItem {
  /**
   * Image field in *Coup de coeur → Carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coup_de_coeur.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type CoupDeCoeurDocumentDataSlicesSlice =
  | TitreSlice
  | RecommandationSlice
  | ParagrapheSlice
  | ImagesSimplesSlice
  | ImagePleineLargeurSlice;

/**
 * Content for Coup de coeur documents
 */
interface CoupDeCoeurDocumentData {
  /**
   * Titre première ligne field in *Coup de coeur*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coup_de_coeur.titre_premiere_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *Coup de coeur*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coup_de_coeur.titre_deuxieme_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Carousel field in *Coup de coeur*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: coup_de_coeur.carousel[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<Simplify<CoupDeCoeurDocumentDataCarouselItem>>;

  /**
   * Slice Zone field in *Coup de coeur*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: coup_de_coeur.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CoupDeCoeurDocumentDataSlicesSlice> /**
   * Meta Description field in *Coup de coeur*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: coup_de_coeur.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Coup de coeur*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coup_de_coeur.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Coup de coeur*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: coup_de_coeur.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Coup de coeur document from Prismic
 *
 * - **API ID**: `coup_de_coeur`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CoupDeCoeurDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CoupDeCoeurDocumentData>,
    "coup_de_coeur",
    Lang
  >;

/**
 * Item in *Footer → Liens*
 */
export interface FooterDocumentDataLiensItem {
  /**
   * Texte field in *Footer → Liens*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.liens[].texte
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texte: prismic.KeyTextField;

  /**
   * Lien field in *Footer → Liens*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.liens[].lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien: prismic.LinkField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Texte field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.texte
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * Liens field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.liens[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  liens: prismic.GroupField<Simplify<FooterDocumentDataLiensItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Formulaire de contact → Catégories*
 */
export interface FormulaireDeContactDocumentDataCategoriesItem {
  /**
   * Catégorie field in *Formulaire de contact → Catégories*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulaire_de_contact.categories[].categorie
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  categorie: prismic.KeyTextField;
}

/**
 * Content for Formulaire de contact documents
 */
interface FormulaireDeContactDocumentData {
  /**
   * Titre première ligne field in *Formulaire de contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulaire_de_contact.titre_premiere_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *Formulaire de contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulaire_de_contact.titre_deuxieme_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Catégories field in *Formulaire de contact*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: formulaire_de_contact.categories[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  categories: prismic.GroupField<
    Simplify<FormulaireDeContactDocumentDataCategoriesItem>
  >;
}

/**
 * Formulaire de contact document from Prismic
 *
 * - **API ID**: `formulaire_de_contact`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FormulaireDeContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FormulaireDeContactDocumentData>,
    "formulaire_de_contact",
    Lang
  >;

/**
 * Item in *Hébergement → Carousel*
 */
export interface HebergementDocumentDataCarouselItem {
  /**
   * Image field in *Hébergement → Carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hebergement.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type HebergementDocumentDataSlicesSlice =
  | TexteImageLargeSlice
  | TexteCarouselSlice
  | TarifsSlice
  | ImageTexteSlice;

/**
 * Content for Hébergement documents
 */
interface HebergementDocumentData {
  /**
   * Titre première ligne field in *Hébergement*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hebergement.titre_premiere_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *Hébergement*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hebergement.titre_deuxieme_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Carousel field in *Hébergement*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hebergement.carousel[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<Simplify<HebergementDocumentDataCarouselItem>>;

  /**
   * Formulaire de contact field in *Hébergement*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hebergement.formulaire_de_contact
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  formulaire_de_contact: prismic.ContentRelationshipField<"formulaire_de_contact">;

  /**
   * Slice Zone field in *Hébergement*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: hebergement.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HebergementDocumentDataSlicesSlice> /**
   * Meta Description field in *Hébergement*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: hebergement.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Hébergement*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hebergement.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Hébergement*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: hebergement.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Hébergement document from Prismic
 *
 * - **API ID**: `hebergement`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HebergementDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HebergementDocumentData>,
    "hebergement",
    Lang
  >;

/**
 * Item in *Menu → Liens*
 */
export interface MenuDocumentDataLiensItem {
  /**
   * Texte field in *Menu → Liens*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.liens[].texte
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texte: prismic.KeyTextField;

  /**
   * Lien field in *Menu → Liens*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.liens[].lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien: prismic.LinkField;
}

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * Titre field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.titre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Liens field in *Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.liens[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  liens: prismic.GroupField<Simplify<MenuDocumentDataLiensItem>>;

  /**
   * Icone Ouvrir Menu field in *Menu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.icone_ouvrir_menu
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icone_ouvrir_menu: prismic.ImageField<never>;

  /**
   * Icone Fermer Menu field in *Menu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.icone_fermer_menu
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icone_fermer_menu: prismic.ImageField<never>;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Paramètres → Réseaux sociaux*
 */
export interface ParametresDocumentDataReseauxSociauxItem {
  /**
   * Logo field in *Paramètres → Réseaux sociaux*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: parametres.reseaux_sociaux[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Lien field in *Paramètres → Réseaux sociaux*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: parametres.reseaux_sociaux[].lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien: prismic.LinkField;
}

/**
 * Content for Paramètres documents
 */
interface ParametresDocumentData {
  /**
   * Titre du site field in *Paramètres*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parametres.titre_du_site
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_du_site: prismic.KeyTextField;

  /**
   * Logo field in *Paramètres*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: parametres.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Téléphone field in *Paramètres*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parametres.telephone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  telephone: prismic.KeyTextField;

  /**
   * Mail field in *Paramètres*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parametres.mail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mail: prismic.KeyTextField;

  /**
   * Réseaux sociaux field in *Paramètres*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: parametres.reseaux_sociaux[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  reseaux_sociaux: prismic.GroupField<
    Simplify<ParametresDocumentDataReseauxSociauxItem>
  >;

  /**
   * Clé Web3Forms field in *Paramètres*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parametres.cle_web3forms
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cle_web3forms: prismic.KeyTextField;
}

/**
 * Paramètres document from Prismic
 *
 * - **API ID**: `parametres`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ParametresDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ParametresDocumentData>,
    "parametres",
    Lang
  >;

export type AllDocumentTypes =
  | AccueilDocument
  | CoupDeCoeurDocument
  | FooterDocument
  | FormulaireDeContactDocument
  | HebergementDocument
  | MenuDocument
  | PageDocument
  | ParametresDocument;

/**
 * Primary content in *ImagePleineLargeur → Primary*
 */
export interface ImagePleineLargeurSliceDefaultPrimary {
  /**
   * Image field in *ImagePleineLargeur → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_pleine_largeur.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImagePleineLargeur Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagePleineLargeurSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImagePleineLargeurSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImagePleineLargeur → Primary*
 */
export interface ImagePleineLargeurSliceImageHautePrimary {
  /**
   * Image field in *ImagePleineLargeur → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_pleine_largeur.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image Haute variation for ImagePleineLargeur Slice
 *
 * - **API ID**: `imageHaute`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagePleineLargeurSliceImageHaute = prismic.SharedSliceVariation<
  "imageHaute",
  Simplify<ImagePleineLargeurSliceImageHautePrimary>,
  never
>;

/**
 * Slice variation for *ImagePleineLargeur*
 */
type ImagePleineLargeurSliceVariation =
  | ImagePleineLargeurSliceDefault
  | ImagePleineLargeurSliceImageHaute;

/**
 * ImagePleineLargeur Shared Slice
 *
 * - **API ID**: `image_pleine_largeur`
 * - **Description**: ImagePleineLargeur
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagePleineLargeurSlice = prismic.SharedSlice<
  "image_pleine_largeur",
  ImagePleineLargeurSliceVariation
>;

/**
 * Primary content in *ImageTexte → Primary*
 */
export interface ImageTexteSliceDefaultPrimary {
  /**
   * Image field in *ImageTexte → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_texte.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Titre field in *ImageTexte → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_texte.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Texte field in *ImageTexte → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_texte.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;
}

/**
 * Default variation for ImageTexte Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTexteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageTexteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageTexte*
 */
type ImageTexteSliceVariation = ImageTexteSliceDefault;

/**
 * ImageTexte Shared Slice
 *
 * - **API ID**: `image_texte`
 * - **Description**: ImageTexte
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTexteSlice = prismic.SharedSlice<
  "image_texte",
  ImageTexteSliceVariation
>;

/**
 * Primary content in *ImagesSimples → Items*
 */
export interface ImagesSimplesSliceDefaultItem {
  /**
   * Image field in *ImagesSimples → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: images_simples.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImagesSimples Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagesSimplesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ImagesSimplesSliceDefaultItem>
>;

/**
 * Slice variation for *ImagesSimples*
 */
type ImagesSimplesSliceVariation = ImagesSimplesSliceDefault;

/**
 * ImagesSimples Shared Slice
 *
 * - **API ID**: `images_simples`
 * - **Description**: ImagesSimples
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagesSimplesSlice = prismic.SharedSlice<
  "images_simples",
  ImagesSimplesSliceVariation
>;

/**
 * Primary content in *Paragraphe → Primary*
 */
export interface ParagrapheSliceDefaultPrimary {
  /**
   * Titre field in *Paragraphe → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: paragraphe.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Texte field in *Paragraphe → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: paragraphe.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;
}

/**
 * Default variation for Paragraphe Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParagrapheSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ParagrapheSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Paragraphe*
 */
type ParagrapheSliceVariation = ParagrapheSliceDefault;

/**
 * Paragraphe Shared Slice
 *
 * - **API ID**: `paragraphe`
 * - **Description**: Paragraphe
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParagrapheSlice = prismic.SharedSlice<
  "paragraphe",
  ParagrapheSliceVariation
>;

/**
 * Primary content in *Recommandation → Primary*
 */
export interface RecommandationSliceDefaultPrimary {
  /**
   * Titre première ligne field in *Recommandation → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recommandation.primary.titre_premiere_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *Recommandation → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recommandation.primary.titre_deuxieme_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Coup de coeur field in *Recommandation → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: recommandation.primary.coup_de_coeur
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  coup_de_coeur: prismic.ContentRelationshipField<"coup_de_coeur">;
}

/**
 * Default variation for Recommandation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecommandationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RecommandationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Recommandation*
 */
type RecommandationSliceVariation = RecommandationSliceDefault;

/**
 * Recommandation Shared Slice
 *
 * - **API ID**: `recommandation`
 * - **Description**: Recommandation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecommandationSlice = prismic.SharedSlice<
  "recommandation",
  RecommandationSliceVariation
>;

/**
 * Primary content in *Tarifs → Primary*
 */
export interface TarifsSliceDefaultPrimary {
  /**
   * Titre field in *Tarifs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tarifs.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Texte field in *Tarifs → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tarifs.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * Image field in *Tarifs → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tarifs.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Tarifs → Items*
 */
export interface TarifsSliceDefaultItem {
  /**
   * Prix field in *Tarifs → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tarifs.items[].prix
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  prix: prismic.KeyTextField;

  /**
   * Description field in *Tarifs → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tarifs.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Tarifs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TarifsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TarifsSliceDefaultPrimary>,
  Simplify<TarifsSliceDefaultItem>
>;

/**
 * Slice variation for *Tarifs*
 */
type TarifsSliceVariation = TarifsSliceDefault;

/**
 * Tarifs Shared Slice
 *
 * - **API ID**: `tarifs`
 * - **Description**: Tarifs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TarifsSlice = prismic.SharedSlice<"tarifs", TarifsSliceVariation>;

/**
 * Primary content in *TexteCarousel → Primary*
 */
export interface TexteCarouselSliceDefaultPrimary {
  /**
   * Titre première ligne field in *TexteCarousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_carousel.primary.titre_premiere_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *TexteCarousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_carousel.primary.titre_deuxieme_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Texte field in *TexteCarousel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_carousel.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;
}

/**
 * Primary content in *TexteCarousel → Items*
 */
export interface TexteCarouselSliceDefaultItem {
  /**
   * Image field in *TexteCarousel → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_carousel.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TexteCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TexteCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TexteCarouselSliceDefaultPrimary>,
  Simplify<TexteCarouselSliceDefaultItem>
>;

/**
 * Slice variation for *TexteCarousel*
 */
type TexteCarouselSliceVariation = TexteCarouselSliceDefault;

/**
 * TexteCarousel Shared Slice
 *
 * - **API ID**: `texte_carousel`
 * - **Description**: TexteCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TexteCarouselSlice = prismic.SharedSlice<
  "texte_carousel",
  TexteCarouselSliceVariation
>;

/**
 * Primary content in *TexteCartesGrille → Primary*
 */
export interface TexteCartesGrilleSliceDefaultPrimary {
  /**
   * Titre première ligne field in *TexteCartesGrille → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_grille.primary.titre_premiere_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *TexteCartesGrille → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_grille.primary.titre_deuxieme_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Texte field in *TexteCartesGrille → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_grille.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;
}

/**
 * Primary content in *TexteCartesGrille → Items*
 */
export interface TexteCartesGrilleSliceDefaultItem {
  /**
   * Titre field in *TexteCartesGrille → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_grille.items[].titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Sous-titre field in *TexteCartesGrille → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_grille.items[].sous_titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sous_titre: prismic.KeyTextField;

  /**
   * Bouton Titre field in *TexteCartesGrille → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_grille.items[].bouton_titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bouton_titre: prismic.KeyTextField;

  /**
   * Bouton Lien field in *TexteCartesGrille → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_grille.items[].bouton_lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  bouton_lien: prismic.LinkField;

  /**
   * Image field in *TexteCartesGrille → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_grille.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TexteCartesGrille Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TexteCartesGrilleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TexteCartesGrilleSliceDefaultPrimary>,
  Simplify<TexteCartesGrilleSliceDefaultItem>
>;

/**
 * Slice variation for *TexteCartesGrille*
 */
type TexteCartesGrilleSliceVariation = TexteCartesGrilleSliceDefault;

/**
 * TexteCartesGrille Shared Slice
 *
 * - **API ID**: `texte_cartes_grille`
 * - **Description**: TexteCartesGrille
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TexteCartesGrilleSlice = prismic.SharedSlice<
  "texte_cartes_grille",
  TexteCartesGrilleSliceVariation
>;

/**
 * Primary content in *TexteCartesVerticales → Primary*
 */
export interface TexteCartesVerticalesSliceDefaultPrimary {
  /**
   * Titre première ligne field in *TexteCartesVerticales → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_verticales.primary.titre_premiere_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *TexteCartesVerticales → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_verticales.primary.titre_deuxieme_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Texte field in *TexteCartesVerticales → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_verticales.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;
}

/**
 * Primary content in *TexteCartesVerticales → Items*
 */
export interface TexteCartesVerticalesSliceDefaultItem {
  /**
   * Titre field in *TexteCartesVerticales → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_verticales.items[].titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Bouton Titre field in *TexteCartesVerticales → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_verticales.items[].bouton_titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bouton_titre: prismic.KeyTextField;

  /**
   * Bouton Lien field in *TexteCartesVerticales → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_verticales.items[].bouton_lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  bouton_lien: prismic.LinkField;

  /**
   * Image field in *TexteCartesVerticales → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_verticales.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TexteCartesVerticales Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TexteCartesVerticalesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TexteCartesVerticalesSliceDefaultPrimary>,
  Simplify<TexteCartesVerticalesSliceDefaultItem>
>;

/**
 * Slice variation for *TexteCartesVerticales*
 */
type TexteCartesVerticalesSliceVariation = TexteCartesVerticalesSliceDefault;

/**
 * TexteCartesVerticales Shared Slice
 *
 * - **API ID**: `texte_cartes_verticales`
 * - **Description**: TexteCartesVerticales
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TexteCartesVerticalesSlice = prismic.SharedSlice<
  "texte_cartes_verticales",
  TexteCartesVerticalesSliceVariation
>;

/**
 * Primary content in *TexteImageLarge → Primary*
 */
export interface TexteImageLargeSliceDefaultPrimary {
  /**
   * Titre field in *TexteImageLarge → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_image_large.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Texte field in *TexteImageLarge → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_image_large.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * Bouton Titre field in *TexteImageLarge → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_image_large.primary.bouton_titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bouton_titre: prismic.KeyTextField;

  /**
   * Bouton Lien field in *TexteImageLarge → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_image_large.primary.bouton_lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  bouton_lien: prismic.LinkField;

  /**
   * Image field in *TexteImageLarge → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_image_large.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TexteImageLarge Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TexteImageLargeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TexteImageLargeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TexteImageLarge*
 */
type TexteImageLargeSliceVariation = TexteImageLargeSliceDefault;

/**
 * TexteImageLarge Shared Slice
 *
 * - **API ID**: `texte_image_large`
 * - **Description**: TexteImageLarge
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TexteImageLargeSlice = prismic.SharedSlice<
  "texte_image_large",
  TexteImageLargeSliceVariation
>;

/**
 * Primary content in *Titre → Primary*
 */
export interface TitreSliceDefaultPrimary {
  /**
   * Titre field in *Titre → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: titre.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Sous-titre field in *Titre → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: titre.primary.sous_titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sous_titre: prismic.KeyTextField;
}

/**
 * Default variation for Titre Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitreSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitreSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Titre*
 */
type TitreSliceVariation = TitreSliceDefault;

/**
 * Titre Shared Slice
 *
 * - **API ID**: `titre`
 * - **Description**: Titre
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitreSlice = prismic.SharedSlice<"titre", TitreSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AccueilDocument,
      AccueilDocumentData,
      AccueilDocumentDataCarouselItem,
      AccueilDocumentDataSlicesSlice,
      CoupDeCoeurDocument,
      CoupDeCoeurDocumentData,
      CoupDeCoeurDocumentDataCarouselItem,
      CoupDeCoeurDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataLiensItem,
      FormulaireDeContactDocument,
      FormulaireDeContactDocumentData,
      FormulaireDeContactDocumentDataCategoriesItem,
      HebergementDocument,
      HebergementDocumentData,
      HebergementDocumentDataCarouselItem,
      HebergementDocumentDataSlicesSlice,
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataLiensItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ParametresDocument,
      ParametresDocumentData,
      ParametresDocumentDataReseauxSociauxItem,
      AllDocumentTypes,
      ImagePleineLargeurSlice,
      ImagePleineLargeurSliceDefaultPrimary,
      ImagePleineLargeurSliceImageHautePrimary,
      ImagePleineLargeurSliceVariation,
      ImagePleineLargeurSliceDefault,
      ImagePleineLargeurSliceImageHaute,
      ImageTexteSlice,
      ImageTexteSliceDefaultPrimary,
      ImageTexteSliceVariation,
      ImageTexteSliceDefault,
      ImagesSimplesSlice,
      ImagesSimplesSliceDefaultItem,
      ImagesSimplesSliceVariation,
      ImagesSimplesSliceDefault,
      ParagrapheSlice,
      ParagrapheSliceDefaultPrimary,
      ParagrapheSliceVariation,
      ParagrapheSliceDefault,
      RecommandationSlice,
      RecommandationSliceDefaultPrimary,
      RecommandationSliceVariation,
      RecommandationSliceDefault,
      TarifsSlice,
      TarifsSliceDefaultPrimary,
      TarifsSliceDefaultItem,
      TarifsSliceVariation,
      TarifsSliceDefault,
      TexteCarouselSlice,
      TexteCarouselSliceDefaultPrimary,
      TexteCarouselSliceDefaultItem,
      TexteCarouselSliceVariation,
      TexteCarouselSliceDefault,
      TexteCartesGrilleSlice,
      TexteCartesGrilleSliceDefaultPrimary,
      TexteCartesGrilleSliceDefaultItem,
      TexteCartesGrilleSliceVariation,
      TexteCartesGrilleSliceDefault,
      TexteCartesVerticalesSlice,
      TexteCartesVerticalesSliceDefaultPrimary,
      TexteCartesVerticalesSliceDefaultItem,
      TexteCartesVerticalesSliceVariation,
      TexteCartesVerticalesSliceDefault,
      TexteImageLargeSlice,
      TexteImageLargeSliceDefaultPrimary,
      TexteImageLargeSliceVariation,
      TexteImageLargeSliceDefault,
      TitreSlice,
      TitreSliceDefaultPrimary,
      TitreSliceVariation,
      TitreSliceDefault,
    };
  }
}
