// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Accueil → Carousel*
 */
export interface AccueilDocumentDataCarouselItem {
  /**
   * Image field in *Accueil → Carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type AccueilDocumentDataSlicesSlice =
  | TexteImageLargeSlice
  | TexteCartesVerticalesSlice
  | TexteCartesGrilleSlice;

/**
 * Content for Accueil documents
 */
interface AccueilDocumentData {
  /**
   * Titre première ligne field in *Accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.titre_premiere_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *Accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.titre_deuxieme_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Carousel field in *Accueil*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.carousel[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<Simplify<AccueilDocumentDataCarouselItem>>;

  /**
   * Formulaire de contact field in *Accueil*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.formulaire_de_contact
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  formulaire_de_contact: prismic.ContentRelationshipField<"formulaire_de_contact">;

  /**
   * Slice Zone field in *Accueil*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AccueilDocumentDataSlicesSlice> /**
   * Meta Description field in *Accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: accueil.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Accueil*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: accueil.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Accueil document from Prismic
 *
 * - **API ID**: `accueil`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AccueilDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AccueilDocumentData>,
    "accueil",
    Lang
  >;

/**
 * Item in *Coup de coeur → Carousel*
 */
export interface CoupDeCoeurDocumentDataCarouselItem {
  /**
   * Image field in *Coup de coeur → Carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coup_de_coeur.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type CoupDeCoeurDocumentDataSlicesSlice =
  | TitreSlice
  | RecommandationSlice
  | ParagrapheSlice
  | ImagesSimplesSlice
  | ImagePleineLargeurSlice;

/**
 * Content for Coup de coeur documents
 */
interface CoupDeCoeurDocumentData {
  /**
   * Titre première ligne field in *Coup de coeur*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coup_de_coeur.titre_premiere_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *Coup de coeur*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coup_de_coeur.titre_deuxieme_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Catégorie field in *Coup de coeur*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Site
   * - **API ID Path**: coup_de_coeur.categorie
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  categorie: prismic.SelectField<
    "Site" | "Randonnée" | "Culinaire" | "Monument" | "Sport" | "Événement",
    "filled"
  >;

  /**
   * Carousel field in *Coup de coeur*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: coup_de_coeur.carousel[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<Simplify<CoupDeCoeurDocumentDataCarouselItem>>;

  /**
   * Slice Zone field in *Coup de coeur*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: coup_de_coeur.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CoupDeCoeurDocumentDataSlicesSlice> /**
   * Meta Description field in *Coup de coeur*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: coup_de_coeur.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Coup de coeur*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coup_de_coeur.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Coup de coeur*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: coup_de_coeur.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Coup de coeur document from Prismic
 *
 * - **API ID**: `coup_de_coeur`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CoupDeCoeurDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CoupDeCoeurDocumentData>,
    "coup_de_coeur",
    Lang
  >;

/**
 * Item in *Coups de coeur → Carousel*
 */
export interface CoupsDeCoeurDocumentDataCarouselItem {
  /**
   * Image field in *Coups de coeur → Carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coups_de_coeur.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type CoupsDeCoeurDocumentDataSlicesSlice = never;

/**
 * Content for Coups de coeur documents
 */
interface CoupsDeCoeurDocumentData {
  /**
   * Titre première ligne field in *Coups de coeur*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coups_de_coeur.titre_premiere_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *Coups de coeur*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coups_de_coeur.titre_deuxieme_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Carousel field in *Coups de coeur*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: coups_de_coeur.carousel[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<Simplify<CoupsDeCoeurDocumentDataCarouselItem>>;

  /**
   * Slice Zone field in *Coups de coeur*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: coups_de_coeur.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CoupsDeCoeurDocumentDataSlicesSlice> /**
   * Meta Description field in *Coups de coeur*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: coups_de_coeur.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Coups de coeur*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coups_de_coeur.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Coups de coeur*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: coups_de_coeur.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Coups de coeur document from Prismic
 *
 * - **API ID**: `coups_de_coeur`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CoupsDeCoeurDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CoupsDeCoeurDocumentData>,
    "coups_de_coeur",
    Lang
  >;

/**
 * Item in *FAQ et avis → Carousel*
 */
export interface FaqEtAvisDocumentDataCarouselItem {
  /**
   * Image field in *FAQ et avis → Carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_et_avis.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type FaqEtAvisDocumentDataSlicesSlice = FoireAuxQuestionsSlice | AvisSlice;

/**
 * Content for FAQ et avis documents
 */
interface FaqEtAvisDocumentData {
  /**
   * Titre première ligne field in *FAQ et avis*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_et_avis.titre_premiere_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *FAQ et avis*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_et_avis.titre_deuxieme_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Carousel field in *FAQ et avis*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_et_avis.carousel[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<Simplify<FaqEtAvisDocumentDataCarouselItem>>;

  /**
   * Slice Zone field in *FAQ et avis*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_et_avis.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FaqEtAvisDocumentDataSlicesSlice> /**
   * Meta Description field in *FAQ et avis*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: faq_et_avis.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *FAQ et avis*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_et_avis.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *FAQ et avis*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: faq_et_avis.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * FAQ et avis document from Prismic
 *
 * - **API ID**: `faq_et_avis`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqEtAvisDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FaqEtAvisDocumentData>,
    "faq_et_avis",
    Lang
  >;

/**
 * Item in *Footer → Liens*
 */
export interface FooterDocumentDataLiensItem {
  /**
   * Texte field in *Footer → Liens*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.liens[].texte
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texte: prismic.KeyTextField;

  /**
   * Lien field in *Footer → Liens*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.liens[].lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien: prismic.LinkField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Texte field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.texte
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * Liens field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.liens[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  liens: prismic.GroupField<Simplify<FooterDocumentDataLiensItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Formulaire de contact → Catégories*
 */
export interface FormulaireDeContactDocumentDataCategoriesItem {
  /**
   * Catégorie field in *Formulaire de contact → Catégories*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulaire_de_contact.categories[].categorie
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  categorie: prismic.KeyTextField;
}

/**
 * Content for Formulaire de contact documents
 */
interface FormulaireDeContactDocumentData {
  /**
   * Titre première ligne field in *Formulaire de contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulaire_de_contact.titre_premiere_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *Formulaire de contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulaire_de_contact.titre_deuxieme_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Catégories field in *Formulaire de contact*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: formulaire_de_contact.categories[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  categories: prismic.GroupField<
    Simplify<FormulaireDeContactDocumentDataCategoriesItem>
  >;
}

/**
 * Formulaire de contact document from Prismic
 *
 * - **API ID**: `formulaire_de_contact`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FormulaireDeContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FormulaireDeContactDocumentData>,
    "formulaire_de_contact",
    Lang
  >;

/**
 * Item in *Hébergement → Carousel*
 */
export interface HebergementDocumentDataCarouselItem {
  /**
   * Image field in *Hébergement → Carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hebergement.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type HebergementDocumentDataSlicesSlice =
  | TexteImageLargeSlice
  | TexteCarouselSlice
  | TarifsSlice
  | ImageTexteSlice;

/**
 * Content for Hébergement documents
 */
interface HebergementDocumentData {
  /**
   * Titre première ligne field in *Hébergement*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hebergement.titre_premiere_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *Hébergement*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hebergement.titre_deuxieme_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Carousel field in *Hébergement*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hebergement.carousel[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<Simplify<HebergementDocumentDataCarouselItem>>;

  /**
   * Formulaire de contact field in *Hébergement*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hebergement.formulaire_de_contact
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  formulaire_de_contact: prismic.ContentRelationshipField<"formulaire_de_contact">;

  /**
   * Slice Zone field in *Hébergement*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: hebergement.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HebergementDocumentDataSlicesSlice> /**
   * Meta Description field in *Hébergement*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: hebergement.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Hébergement*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hebergement.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Hébergement*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: hebergement.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Hébergement document from Prismic
 *
 * - **API ID**: `hebergement`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HebergementDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HebergementDocumentData>,
    "hebergement",
    Lang
  >;

/**
 * Item in *Histoire → Carousel*
 */
export interface HistoireDocumentDataCarouselItem {
  /**
   * Image field in *Histoire → Carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: histoire.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type HistoireDocumentDataSlicesSlice =
  | GrilleImagesSlice
  | ImagePleineLargeurSlice
  | AssemblageSlice
  | TitreSlice
  | ParagrapheSlice;

/**
 * Content for Histoire documents
 */
interface HistoireDocumentData {
  /**
   * Titre première ligne field in *Histoire*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: histoire.titre_premiere_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *Histoire*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: histoire.titre_deuxieme_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Carousel field in *Histoire*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: histoire.carousel[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<Simplify<HistoireDocumentDataCarouselItem>>;

  /**
   * Slice Zone field in *Histoire*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: histoire.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HistoireDocumentDataSlicesSlice> /**
   * Meta Description field in *Histoire*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: histoire.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Histoire*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: histoire.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Histoire*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: histoire.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Histoire document from Prismic
 *
 * - **API ID**: `histoire`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HistoireDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HistoireDocumentData>,
    "histoire",
    Lang
  >;

/**
 * Item in *Menu → Liens*
 */
export interface MenuDocumentDataLiensItem {
  /**
   * Texte field in *Menu → Liens*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.liens[].texte
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texte: prismic.KeyTextField;

  /**
   * Lien field in *Menu → Liens*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.liens[].lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien: prismic.LinkField;
}

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * Titre field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.titre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Liens field in *Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.liens[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  liens: prismic.GroupField<Simplify<MenuDocumentDataLiensItem>>;

  /**
   * Icone Ouvrir Menu field in *Menu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.icone_ouvrir_menu
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icone_ouvrir_menu: prismic.ImageField<never>;

  /**
   * Icone Fermer Menu field in *Menu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.icone_fermer_menu
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icone_fermer_menu: prismic.ImageField<never>;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

/**
 * Item in *Où sommes nous → Carousel*
 */
export interface OuSommesNousDocumentDataCarouselItem {
  /**
   * Image field in *Où sommes nous → Carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ou_sommes_nous.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type OuSommesNousDocumentDataSlicesSlice =
  | GrilleImagesTitresSlice
  | TexteImageLargeSlice
  | ImagesSimplesSlice
  | TitreSlice
  | ParagrapheSlice;

/**
 * Content for Où sommes nous documents
 */
interface OuSommesNousDocumentData {
  /**
   * Titre première ligne field in *Où sommes nous*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ou_sommes_nous.titre_premiere_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *Où sommes nous*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ou_sommes_nous.titre_deuxieme_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Carousel field in *Où sommes nous*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ou_sommes_nous.carousel[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<Simplify<OuSommesNousDocumentDataCarouselItem>>;

  /**
   * Slice Zone field in *Où sommes nous*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: ou_sommes_nous.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OuSommesNousDocumentDataSlicesSlice> /**
   * Meta Description field in *Où sommes nous*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: ou_sommes_nous.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Où sommes nous*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ou_sommes_nous.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Où sommes nous*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: ou_sommes_nous.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Où sommes nous document from Prismic
 *
 * - **API ID**: `ou_sommes_nous`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OuSommesNousDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<OuSommesNousDocumentData>,
    "ou_sommes_nous",
    Lang
  >;

/**
 * Item in *Page → Carousel*
 */
export interface PageDocumentDataCarouselItem {
  /**
   * Image field in *Page → Carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type PageDocumentDataSlicesSlice =
  | TexteCarouselSlice
  | TarifsSlice
  | GrilleImagesTitresSlice
  | TexteImageLargeSlice
  | TexteCartesVerticalesSlice
  | ImagePleineLargeurSlice
  | TexteCartesGrilleSlice
  | ImagesSimplesSlice
  | ImageTexteSlice
  | GrilleImagesSlice
  | TitreSlice
  | AssemblageSlice
  | RecommandationSlice
  | ParagrapheSlice
  | AvisSlice
  | FoireAuxQuestionsSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Titre première ligne field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.titre_premiere_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.titre_deuxieme_ligne
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Carousel field in *Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: page.carousel[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<Simplify<PageDocumentDataCarouselItem>>;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type PageContactDocumentDataSlicesSlice = never;

/**
 * Content for Page contact documents
 */
interface PageContactDocumentData {
  /**
   * Formulaire de contact field in *Page contact*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.formulaire_de_contact
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  formulaire_de_contact: prismic.ContentRelationshipField<"formulaire_de_contact">;

  /**
   * Image field in *Page contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Page contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageContactDocumentDataSlicesSlice> /**
   * Meta Description field in *Page contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page_contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Page contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page_contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Page contact document from Prismic
 *
 * - **API ID**: `page_contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PageContactDocumentData>,
    "page_contact",
    Lang
  >;

/**
 * Item in *Paramètres → Réseaux sociaux*
 */
export interface ParametresDocumentDataReseauxSociauxItem {
  /**
   * Logo field in *Paramètres → Réseaux sociaux*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: parametres.reseaux_sociaux[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Lien field in *Paramètres → Réseaux sociaux*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: parametres.reseaux_sociaux[].lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien: prismic.LinkField;
}

/**
 * Content for Paramètres documents
 */
interface ParametresDocumentData {
  /**
   * Titre du site field in *Paramètres*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parametres.titre_du_site
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_du_site: prismic.KeyTextField;

  /**
   * Logo field in *Paramètres*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: parametres.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Téléphone field in *Paramètres*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parametres.telephone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  telephone: prismic.KeyTextField;

  /**
   * Mail field in *Paramètres*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parametres.mail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mail: prismic.KeyTextField;

  /**
   * Réseaux sociaux field in *Paramètres*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: parametres.reseaux_sociaux[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  reseaux_sociaux: prismic.GroupField<
    Simplify<ParametresDocumentDataReseauxSociauxItem>
  >;

  /**
   * Clé Web3Forms field in *Paramètres*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parametres.cle_web3forms
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cle_web3forms: prismic.KeyTextField;
}

/**
 * Paramètres document from Prismic
 *
 * - **API ID**: `parametres`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ParametresDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ParametresDocumentData>,
    "parametres",
    Lang
  >;

export type AllDocumentTypes =
  | AccueilDocument
  | CoupDeCoeurDocument
  | CoupsDeCoeurDocument
  | FaqEtAvisDocument
  | FooterDocument
  | FormulaireDeContactDocument
  | HebergementDocument
  | HistoireDocument
  | MenuDocument
  | OuSommesNousDocument
  | PageDocument
  | PageContactDocument
  | ParametresDocument;

/**
 * Primary content in *Assemblage → Items*
 */
export interface AssemblageSliceDefaultItem {
  /**
   * Titre field in *Assemblage → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: assemblage.items[].titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Texte field in *Assemblage → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: assemblage.items[].texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * Image field in *Assemblage → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: assemblage.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Assemblage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AssemblageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<AssemblageSliceDefaultItem>
>;

/**
 * Slice variation for *Assemblage*
 */
type AssemblageSliceVariation = AssemblageSliceDefault;

/**
 * Assemblage Shared Slice
 *
 * - **API ID**: `assemblage`
 * - **Description**: Assemblage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AssemblageSlice = prismic.SharedSlice<
  "assemblage",
  AssemblageSliceVariation
>;

/**
 * Primary content in *Avis → Primary*
 */
export interface AvisSliceDefaultPrimary {
  /**
   * Titre field in *Avis → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: avis.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;
}

/**
 * Primary content in *Avis → Items*
 */
export interface AvisSliceDefaultItem {
  /**
   * Texte field in *Avis → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: avis.items[].texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * Auteur field in *Avis → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: avis.items[].auteur
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  auteur: prismic.KeyTextField;
}

/**
 * Default variation for Avis Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AvisSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AvisSliceDefaultPrimary>,
  Simplify<AvisSliceDefaultItem>
>;

/**
 * Slice variation for *Avis*
 */
type AvisSliceVariation = AvisSliceDefault;

/**
 * Avis Shared Slice
 *
 * - **API ID**: `avis`
 * - **Description**: Avis
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AvisSlice = prismic.SharedSlice<"avis", AvisSliceVariation>;

/**
 * Primary content in *FoireAuxQuestions → Primary*
 */
export interface FoireAuxQuestionsSliceDefaultPrimary {
  /**
   * Titre première ligne field in *FoireAuxQuestions → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foire_aux_questions.primary.titre_premiere_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *FoireAuxQuestions → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foire_aux_questions.primary.titre_deuxieme_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;
}

/**
 * Primary content in *FoireAuxQuestions → Items*
 */
export interface FoireAuxQuestionsSliceDefaultItem {
  /**
   * Question field in *FoireAuxQuestions → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foire_aux_questions.items[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Réponse field in *FoireAuxQuestions → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foire_aux_questions.items[].reponse
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  reponse: prismic.RichTextField;
}

/**
 * Default variation for FoireAuxQuestions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FoireAuxQuestionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FoireAuxQuestionsSliceDefaultPrimary>,
  Simplify<FoireAuxQuestionsSliceDefaultItem>
>;

/**
 * Slice variation for *FoireAuxQuestions*
 */
type FoireAuxQuestionsSliceVariation = FoireAuxQuestionsSliceDefault;

/**
 * FoireAuxQuestions Shared Slice
 *
 * - **API ID**: `foire_aux_questions`
 * - **Description**: FoireAuxQuestions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FoireAuxQuestionsSlice = prismic.SharedSlice<
  "foire_aux_questions",
  FoireAuxQuestionsSliceVariation
>;

/**
 * Primary content in *GrilleImages → Primary*
 */
export interface GrilleImagesSliceDefaultPrimary {
  /**
   * Image 1 field in *GrilleImages → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grille_images.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *GrilleImages → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grille_images.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *GrilleImages → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grille_images.primary.image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;
}

/**
 * Default variation for GrilleImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GrilleImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GrilleImagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GrilleImages*
 */
type GrilleImagesSliceVariation = GrilleImagesSliceDefault;

/**
 * GrilleImages Shared Slice
 *
 * - **API ID**: `grille_images`
 * - **Description**: GrilleImages
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GrilleImagesSlice = prismic.SharedSlice<
  "grille_images",
  GrilleImagesSliceVariation
>;

/**
 * Primary content in *GrilleImagesTitres → Primary*
 */
export interface GrilleImagesTitresSliceDefaultPrimary {
  /**
   * Image 1 field in *GrilleImagesTitres → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grille_images_titres.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *GrilleImagesTitres → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grille_images_titres.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *GrilleImagesTitres → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grille_images_titres.primary.image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;
}

/**
 * Primary content in *GrilleImagesTitres → Items*
 */
export interface GrilleImagesTitresSliceDefaultItem {
  /**
   * Titre 1 field in *GrilleImagesTitres → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grille_images_titres.items[].titre_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_1: prismic.KeyTextField;

  /**
   * Titre 2 field in *GrilleImagesTitres → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grille_images_titres.items[].titre_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_2: prismic.KeyTextField;

  /**
   * Image 1 field in *GrilleImagesTitres → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grille_images_titres.items[].image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *GrilleImagesTitres → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grille_images_titres.items[].image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *GrilleImagesTitres → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grille_images_titres.items[].image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;
}

/**
 * Default variation for GrilleImagesTitres Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GrilleImagesTitresSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GrilleImagesTitresSliceDefaultPrimary>,
  Simplify<GrilleImagesTitresSliceDefaultItem>
>;

/**
 * Slice variation for *GrilleImagesTitres*
 */
type GrilleImagesTitresSliceVariation = GrilleImagesTitresSliceDefault;

/**
 * GrilleImagesTitres Shared Slice
 *
 * - **API ID**: `grille_images_titres`
 * - **Description**: GrilleImagesTitres
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GrilleImagesTitresSlice = prismic.SharedSlice<
  "grille_images_titres",
  GrilleImagesTitresSliceVariation
>;

/**
 * Primary content in *ImagePleineLargeur → Primary*
 */
export interface ImagePleineLargeurSliceDefaultPrimary {
  /**
   * Image field in *ImagePleineLargeur → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_pleine_largeur.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImagePleineLargeur Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagePleineLargeurSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImagePleineLargeurSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImagePleineLargeur → Primary*
 */
export interface ImagePleineLargeurSliceImageHautePrimary {
  /**
   * Image field in *ImagePleineLargeur → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_pleine_largeur.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image Haute variation for ImagePleineLargeur Slice
 *
 * - **API ID**: `imageHaute`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagePleineLargeurSliceImageHaute = prismic.SharedSliceVariation<
  "imageHaute",
  Simplify<ImagePleineLargeurSliceImageHautePrimary>,
  never
>;

/**
 * Primary content in *ImagePleineLargeur → Primary*
 */
export interface ImagePleineLargeurSliceImageTresHautePrimary {
  /**
   * Image field in *ImagePleineLargeur → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_pleine_largeur.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image Très Haute variation for ImagePleineLargeur Slice
 *
 * - **API ID**: `imageTresHaute`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagePleineLargeurSliceImageTresHaute =
  prismic.SharedSliceVariation<
    "imageTresHaute",
    Simplify<ImagePleineLargeurSliceImageTresHautePrimary>,
    never
  >;

/**
 * Slice variation for *ImagePleineLargeur*
 */
type ImagePleineLargeurSliceVariation =
  | ImagePleineLargeurSliceDefault
  | ImagePleineLargeurSliceImageHaute
  | ImagePleineLargeurSliceImageTresHaute;

/**
 * ImagePleineLargeur Shared Slice
 *
 * - **API ID**: `image_pleine_largeur`
 * - **Description**: ImagePleineLargeur
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagePleineLargeurSlice = prismic.SharedSlice<
  "image_pleine_largeur",
  ImagePleineLargeurSliceVariation
>;

/**
 * Primary content in *ImageTexte → Primary*
 */
export interface ImageTexteSliceDefaultPrimary {
  /**
   * Image field in *ImageTexte → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_texte.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Titre field in *ImageTexte → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_texte.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Texte field in *ImageTexte → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_texte.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;
}

/**
 * Default variation for ImageTexte Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTexteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageTexteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageTexte*
 */
type ImageTexteSliceVariation = ImageTexteSliceDefault;

/**
 * ImageTexte Shared Slice
 *
 * - **API ID**: `image_texte`
 * - **Description**: ImageTexte
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTexteSlice = prismic.SharedSlice<
  "image_texte",
  ImageTexteSliceVariation
>;

/**
 * Primary content in *ImagesSimples → Items*
 */
export interface ImagesSimplesSliceDefaultItem {
  /**
   * Image field in *ImagesSimples → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: images_simples.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImagesSimples Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagesSimplesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ImagesSimplesSliceDefaultItem>
>;

/**
 * Primary content in *ImagesSimples → Items*
 */
export interface ImagesSimplesSliceMultiLignesItem {
  /**
   * Image field in *ImagesSimples → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: images_simples.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Multi-lignes variation for ImagesSimples Slice
 *
 * - **API ID**: `multiLignes`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagesSimplesSliceMultiLignes = prismic.SharedSliceVariation<
  "multiLignes",
  Record<string, never>,
  Simplify<ImagesSimplesSliceMultiLignesItem>
>;

/**
 * Slice variation for *ImagesSimples*
 */
type ImagesSimplesSliceVariation =
  | ImagesSimplesSliceDefault
  | ImagesSimplesSliceMultiLignes;

/**
 * ImagesSimples Shared Slice
 *
 * - **API ID**: `images_simples`
 * - **Description**: ImagesSimples
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagesSimplesSlice = prismic.SharedSlice<
  "images_simples",
  ImagesSimplesSliceVariation
>;

/**
 * Primary content in *Paragraphe → Primary*
 */
export interface ParagrapheSliceDefaultPrimary {
  /**
   * Titre field in *Paragraphe → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: paragraphe.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Texte field in *Paragraphe → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: paragraphe.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;
}

/**
 * Default variation for Paragraphe Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParagrapheSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ParagrapheSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Paragraphe*
 */
type ParagrapheSliceVariation = ParagrapheSliceDefault;

/**
 * Paragraphe Shared Slice
 *
 * - **API ID**: `paragraphe`
 * - **Description**: Paragraphe
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParagrapheSlice = prismic.SharedSlice<
  "paragraphe",
  ParagrapheSliceVariation
>;

/**
 * Primary content in *Recommandation → Primary*
 */
export interface RecommandationSliceDefaultPrimary {
  /**
   * Titre première ligne field in *Recommandation → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recommandation.primary.titre_premiere_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *Recommandation → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recommandation.primary.titre_deuxieme_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Coup de coeur field in *Recommandation → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: recommandation.primary.coup_de_coeur
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  coup_de_coeur: prismic.ContentRelationshipField<"coup_de_coeur">;
}

/**
 * Default variation for Recommandation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecommandationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RecommandationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Recommandation*
 */
type RecommandationSliceVariation = RecommandationSliceDefault;

/**
 * Recommandation Shared Slice
 *
 * - **API ID**: `recommandation`
 * - **Description**: Recommandation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecommandationSlice = prismic.SharedSlice<
  "recommandation",
  RecommandationSliceVariation
>;

/**
 * Primary content in *Tarifs → Primary*
 */
export interface TarifsSliceDefaultPrimary {
  /**
   * Titre field in *Tarifs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tarifs.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Texte field in *Tarifs → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tarifs.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * Image field in *Tarifs → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tarifs.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Tarifs → Items*
 */
export interface TarifsSliceDefaultItem {
  /**
   * Prix field in *Tarifs → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tarifs.items[].prix
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  prix: prismic.KeyTextField;

  /**
   * Description field in *Tarifs → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tarifs.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Tarifs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TarifsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TarifsSliceDefaultPrimary>,
  Simplify<TarifsSliceDefaultItem>
>;

/**
 * Slice variation for *Tarifs*
 */
type TarifsSliceVariation = TarifsSliceDefault;

/**
 * Tarifs Shared Slice
 *
 * - **API ID**: `tarifs`
 * - **Description**: Tarifs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TarifsSlice = prismic.SharedSlice<"tarifs", TarifsSliceVariation>;

/**
 * Primary content in *TexteCarousel → Primary*
 */
export interface TexteCarouselSliceDefaultPrimary {
  /**
   * Titre première ligne field in *TexteCarousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_carousel.primary.titre_premiere_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *TexteCarousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_carousel.primary.titre_deuxieme_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Texte field in *TexteCarousel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_carousel.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;
}

/**
 * Primary content in *TexteCarousel → Items*
 */
export interface TexteCarouselSliceDefaultItem {
  /**
   * Image field in *TexteCarousel → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_carousel.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TexteCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TexteCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TexteCarouselSliceDefaultPrimary>,
  Simplify<TexteCarouselSliceDefaultItem>
>;

/**
 * Slice variation for *TexteCarousel*
 */
type TexteCarouselSliceVariation = TexteCarouselSliceDefault;

/**
 * TexteCarousel Shared Slice
 *
 * - **API ID**: `texte_carousel`
 * - **Description**: TexteCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TexteCarouselSlice = prismic.SharedSlice<
  "texte_carousel",
  TexteCarouselSliceVariation
>;

/**
 * Primary content in *CoupsDeCoeur → Primary*
 */
export interface TexteCartesGrilleSliceDefaultPrimary {
  /**
   * Titre première ligne field in *CoupsDeCoeur → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_grille.primary.titre_premiere_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *CoupsDeCoeur → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_grille.primary.titre_deuxieme_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Texte field in *CoupsDeCoeur → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_grille.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;
}

/**
 * Primary content in *CoupsDeCoeur → Items*
 */
export interface TexteCartesGrilleSliceDefaultItem {
  /**
   * Coup de coeur field in *CoupsDeCoeur → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_grille.items[].coup_de_coeur
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  coup_de_coeur: prismic.ContentRelationshipField<"coup_de_coeur">;
}

/**
 * Default variation for CoupsDeCoeur Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TexteCartesGrilleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TexteCartesGrilleSliceDefaultPrimary>,
  Simplify<TexteCartesGrilleSliceDefaultItem>
>;

/**
 * Slice variation for *CoupsDeCoeur*
 */
type TexteCartesGrilleSliceVariation = TexteCartesGrilleSliceDefault;

/**
 * CoupsDeCoeur Shared Slice
 *
 * - **API ID**: `texte_cartes_grille`
 * - **Description**: TexteCartesGrille
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TexteCartesGrilleSlice = prismic.SharedSlice<
  "texte_cartes_grille",
  TexteCartesGrilleSliceVariation
>;

/**
 * Primary content in *TexteCartesVerticales → Primary*
 */
export interface TexteCartesVerticalesSliceDefaultPrimary {
  /**
   * Titre première ligne field in *TexteCartesVerticales → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_verticales.primary.titre_premiere_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_premiere_ligne: prismic.KeyTextField;

  /**
   * Titre deuxième ligne field in *TexteCartesVerticales → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_verticales.primary.titre_deuxieme_ligne
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_deuxieme_ligne: prismic.KeyTextField;

  /**
   * Texte field in *TexteCartesVerticales → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_verticales.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;
}

/**
 * Primary content in *TexteCartesVerticales → Items*
 */
export interface TexteCartesVerticalesSliceDefaultItem {
  /**
   * Titre field in *TexteCartesVerticales → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_verticales.items[].titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Bouton Titre field in *TexteCartesVerticales → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_verticales.items[].bouton_titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bouton_titre: prismic.KeyTextField;

  /**
   * Bouton Lien field in *TexteCartesVerticales → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_verticales.items[].bouton_lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  bouton_lien: prismic.LinkField;

  /**
   * Image field in *TexteCartesVerticales → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_cartes_verticales.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TexteCartesVerticales Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TexteCartesVerticalesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TexteCartesVerticalesSliceDefaultPrimary>,
  Simplify<TexteCartesVerticalesSliceDefaultItem>
>;

/**
 * Slice variation for *TexteCartesVerticales*
 */
type TexteCartesVerticalesSliceVariation = TexteCartesVerticalesSliceDefault;

/**
 * TexteCartesVerticales Shared Slice
 *
 * - **API ID**: `texte_cartes_verticales`
 * - **Description**: TexteCartesVerticales
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TexteCartesVerticalesSlice = prismic.SharedSlice<
  "texte_cartes_verticales",
  TexteCartesVerticalesSliceVariation
>;

/**
 * Primary content in *TexteImageLarge → Primary*
 */
export interface TexteImageLargeSliceDefaultPrimary {
  /**
   * Titre field in *TexteImageLarge → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_image_large.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Texte field in *TexteImageLarge → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_image_large.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * Bouton Titre field in *TexteImageLarge → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_image_large.primary.bouton_titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bouton_titre: prismic.KeyTextField;

  /**
   * Bouton Lien field in *TexteImageLarge → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_image_large.primary.bouton_lien
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  bouton_lien: prismic.LinkField;

  /**
   * Image field in *TexteImageLarge → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_image_large.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TexteImageLarge Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TexteImageLargeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TexteImageLargeSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TexteImageLarge → Primary*
 */
export interface TexteImageLargeSliceTexteSeulPrimary {
  /**
   * Texte field in *TexteImageLarge → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_image_large.primary.texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * Image field in *TexteImageLarge → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: texte_image_large.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * TexteSeul variation for TexteImageLarge Slice
 *
 * - **API ID**: `texteSeul`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TexteImageLargeSliceTexteSeul = prismic.SharedSliceVariation<
  "texteSeul",
  Simplify<TexteImageLargeSliceTexteSeulPrimary>,
  never
>;

/**
 * Slice variation for *TexteImageLarge*
 */
type TexteImageLargeSliceVariation =
  | TexteImageLargeSliceDefault
  | TexteImageLargeSliceTexteSeul;

/**
 * TexteImageLarge Shared Slice
 *
 * - **API ID**: `texte_image_large`
 * - **Description**: TexteImageLarge
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TexteImageLargeSlice = prismic.SharedSlice<
  "texte_image_large",
  TexteImageLargeSliceVariation
>;

/**
 * Primary content in *Titre → Primary*
 */
export interface TitreSliceDefaultPrimary {
  /**
   * Titre field in *Titre → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: titre.primary.titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Sous-titre field in *Titre → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: titre.primary.sous_titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sous_titre: prismic.KeyTextField;
}

/**
 * Default variation for Titre Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitreSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitreSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Titre*
 */
type TitreSliceVariation = TitreSliceDefault;

/**
 * Titre Shared Slice
 *
 * - **API ID**: `titre`
 * - **Description**: Titre
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitreSlice = prismic.SharedSlice<"titre", TitreSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AccueilDocument,
      AccueilDocumentData,
      AccueilDocumentDataCarouselItem,
      AccueilDocumentDataSlicesSlice,
      CoupDeCoeurDocument,
      CoupDeCoeurDocumentData,
      CoupDeCoeurDocumentDataCarouselItem,
      CoupDeCoeurDocumentDataSlicesSlice,
      CoupsDeCoeurDocument,
      CoupsDeCoeurDocumentData,
      CoupsDeCoeurDocumentDataCarouselItem,
      CoupsDeCoeurDocumentDataSlicesSlice,
      FaqEtAvisDocument,
      FaqEtAvisDocumentData,
      FaqEtAvisDocumentDataCarouselItem,
      FaqEtAvisDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataLiensItem,
      FormulaireDeContactDocument,
      FormulaireDeContactDocumentData,
      FormulaireDeContactDocumentDataCategoriesItem,
      HebergementDocument,
      HebergementDocumentData,
      HebergementDocumentDataCarouselItem,
      HebergementDocumentDataSlicesSlice,
      HistoireDocument,
      HistoireDocumentData,
      HistoireDocumentDataCarouselItem,
      HistoireDocumentDataSlicesSlice,
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataLiensItem,
      OuSommesNousDocument,
      OuSommesNousDocumentData,
      OuSommesNousDocumentDataCarouselItem,
      OuSommesNousDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataCarouselItem,
      PageDocumentDataSlicesSlice,
      PageContactDocument,
      PageContactDocumentData,
      PageContactDocumentDataSlicesSlice,
      ParametresDocument,
      ParametresDocumentData,
      ParametresDocumentDataReseauxSociauxItem,
      AllDocumentTypes,
      AssemblageSlice,
      AssemblageSliceDefaultItem,
      AssemblageSliceVariation,
      AssemblageSliceDefault,
      AvisSlice,
      AvisSliceDefaultPrimary,
      AvisSliceDefaultItem,
      AvisSliceVariation,
      AvisSliceDefault,
      FoireAuxQuestionsSlice,
      FoireAuxQuestionsSliceDefaultPrimary,
      FoireAuxQuestionsSliceDefaultItem,
      FoireAuxQuestionsSliceVariation,
      FoireAuxQuestionsSliceDefault,
      GrilleImagesSlice,
      GrilleImagesSliceDefaultPrimary,
      GrilleImagesSliceVariation,
      GrilleImagesSliceDefault,
      GrilleImagesTitresSlice,
      GrilleImagesTitresSliceDefaultPrimary,
      GrilleImagesTitresSliceDefaultItem,
      GrilleImagesTitresSliceVariation,
      GrilleImagesTitresSliceDefault,
      ImagePleineLargeurSlice,
      ImagePleineLargeurSliceDefaultPrimary,
      ImagePleineLargeurSliceImageHautePrimary,
      ImagePleineLargeurSliceImageTresHautePrimary,
      ImagePleineLargeurSliceVariation,
      ImagePleineLargeurSliceDefault,
      ImagePleineLargeurSliceImageHaute,
      ImagePleineLargeurSliceImageTresHaute,
      ImageTexteSlice,
      ImageTexteSliceDefaultPrimary,
      ImageTexteSliceVariation,
      ImageTexteSliceDefault,
      ImagesSimplesSlice,
      ImagesSimplesSliceDefaultItem,
      ImagesSimplesSliceMultiLignesItem,
      ImagesSimplesSliceVariation,
      ImagesSimplesSliceDefault,
      ImagesSimplesSliceMultiLignes,
      ParagrapheSlice,
      ParagrapheSliceDefaultPrimary,
      ParagrapheSliceVariation,
      ParagrapheSliceDefault,
      RecommandationSlice,
      RecommandationSliceDefaultPrimary,
      RecommandationSliceVariation,
      RecommandationSliceDefault,
      TarifsSlice,
      TarifsSliceDefaultPrimary,
      TarifsSliceDefaultItem,
      TarifsSliceVariation,
      TarifsSliceDefault,
      TexteCarouselSlice,
      TexteCarouselSliceDefaultPrimary,
      TexteCarouselSliceDefaultItem,
      TexteCarouselSliceVariation,
      TexteCarouselSliceDefault,
      TexteCartesGrilleSlice,
      TexteCartesGrilleSliceDefaultPrimary,
      TexteCartesGrilleSliceDefaultItem,
      TexteCartesGrilleSliceVariation,
      TexteCartesGrilleSliceDefault,
      TexteCartesVerticalesSlice,
      TexteCartesVerticalesSliceDefaultPrimary,
      TexteCartesVerticalesSliceDefaultItem,
      TexteCartesVerticalesSliceVariation,
      TexteCartesVerticalesSliceDefault,
      TexteImageLargeSlice,
      TexteImageLargeSliceDefaultPrimary,
      TexteImageLargeSliceTexteSeulPrimary,
      TexteImageLargeSliceVariation,
      TexteImageLargeSliceDefault,
      TexteImageLargeSliceTexteSeul,
      TitreSlice,
      TitreSliceDefaultPrimary,
      TitreSliceVariation,
      TitreSliceDefault,
    };
  }
}
